# Note - deno is for nvim's markdown previewer

- shell:
  # Various compilers/languages
  - |
    if [[ "$(./sys id)" == "arch" ]]; then
      sudo pacman -S --noconfirm --needed jdk-openjdk clang python python-pip deno uv
    elif [[ "$(./sys id)" != "arch" ]]; then
      brew install java llvm python typst deno uv
    fi
