- link:
    ~/.config/qt6ct/qt6ct.conf: styling/qt/qt6ct.conf

- shell:
    - |
      if [[ "$(./sys id)" == "arch" ]]; then
        sudo pacman -S --noconfirm --needed qt5-wayland qt6-wayland breeze breeze-icons
        yay -S --noconfirm --needed --answerdiff None --answerclean None qt6ct-kde
      elif [[ "$(./sys id)" != "arch" ]]; then
        echo "To be added"
      fi

# For qt5 theming
# pacman -S qt5ct breeze5
# Also change qt_qpa_platformtheme to qt5ct and symlink qt5ct.conf file
#
# If using regular qt6ct package you will need to change qt6ct.conf to use a builtin qt6ct theme file rather than the Breeze.colors ones.
#
# Could also use hyprqt6engine as a replacement for qt6ct-kde.
# Would require changing qt_qpa_platformtheme to hyprqt6engine as well as installing the package
