- link:
    ~/.config/bat: tui/bat
    ~/.config/btop: tui/btop
    ~/.config/qalculate/qalc.cfg: tui/qalc/qalc.cfg
    ~/.config/cava/config: tui/cava/config
    ~/.config/fastfetch/:
      path: tui/fastfetch/*.jsonc
      glob: true
    ~/.config/yazi:
      path: tui/yazi/*
      glob: true

- shell:
    - |
      if [[ "$(./sys id)" == "arch" ]]; then
        sudo pacman -S --noconfirm --needed bat yazi btop fastfetch bc libqalculate
      elif [[ "$(./sys id)" == "ubuntu" ]]; then
        brew install bat yazi btop fastfetch
        sudo apt install -y bc qalc
      elif [[ "$(./sys id)" == "fedora" ]]; then
        brew install bat yazi btop fastfetch
        sudo dnf install -y bc libqalculate
      elif [[ "$(./sys id)" == "mac" ]]; then
        brew install bat yazi btop fastfetch bc libqalculate
      fi
    - bat cache --build
    - cd ~/.config/yazi && ya pkg install && ya pkg upgrade
