#!/usr/bin/env bash
set -euo pipefail

#Note - deps installed: git, python, homebrew, make, gcc

# Detect OS
OS="unknown"
if [[ "$(uname -s)" == "Darwin" ]]; then
    OS="mac"
    BREW_BIN="/opt/homebrew/bin/brew"
elif [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
    BREW_BIN="/home/linuxbrew/.linuxbrew/bin/brew"
fi

DOTFILES_REPO="git@github.com:dommcdev/dotfiles.git"
DOTFILES_DIR="$HOME/dev/dotfiles"


start_sudo_loop() {
    sudo -v
    while true; do sudo -n true; sleep 30; kill -0 "$$" || exit; done 2>/dev/null &
}

echo -e "Starting configuration for $OS...\n\n"
start_sudo_loop

# Check if Homebrew is already installed
if [ ! -x "$BREW_BIN" ]; then
    echo "Homebrew not found. Installing..."
    NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    eval "$("$BREW_BIN" shellenv)"
    echo "Homebrew installation complete."
else
    echo "Homebrew is already installed. Skipping installation."
    eval "$("$BREW_BIN" shellenv)"
fi

# Install dotfile dependencies
echo "Installing dotfile dependencies..."
if [[ "$OS" == "ubuntu" ]]; then
    sudo apt update && sudo apt install -y python3 git make gcc
elif [[ "$OS" == "fedora" ]]; then
    sudo dnf install -y python3 git make gcc
elif [[ "$OS" == "mac" ]]; then
    brew install python3 git make gcc
fi

# Clone dotfiles
if [ ! -d "$DOTFILES_DIR" ]; then
    echo "Cloning dotfiles..."
    git clone "$DOTFILES_REPO" "$DOTFILES_DIR"
else
    echo "Dotfiles directory already exists. Skipping clone."
fi

# Run dotfiles
echo "Running dotfiles installer..."
cd "$DOTFILES_DIR" && ./install
