[audio]
enable_sounds = true

[bar]
order = [ "default" ]

    [bar.default]
    capsule_radius = 0
    center = [ "date", "center_spacer", "clock", "center_spacer", "weather", "center_spacer", "privacy", "widget" ]
    end = [
        "tray",
        "battery",
        "right_spacer",
        "network",
        "right_spacer",
        "bluetooth",
        "right_spacer",
        "volume",
        "right_spacer",
        "brightness",
        "right_spacer",
        "notifications",
        "right_spacer",
        "control-center"
    ]
    font_family = "Inter"
    margin_edge = 0
    margin_ends = 8
    radius = 0
    start = [ "workspaces", "left_spacer", "cpu", "ram", "left_spacer", "media" ]

[battery.device."/org/freedesktop/UPower/devices/battery_hidpp_battery_0"]
warning_threshold = 10

[battery.device."/org/freedesktop/UPower/devices/headset_dev_95_05_BB_29_BF_05"]
warning_threshold = 10

[brightness]
enable_ddcutil = true
minimum_brightness = 0.04999999888241291

[calendar]
enabled = true

    [calendar.account.personal_google]
    color = "primary"
    type = "google"

[control_center]
sidebar_section = "none"
width = 750

    [control_center.calendar]
    show_events_card = false

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "noctalia/screen_recorder:toggle"

    [[control_center.shortcuts]]
    type = "nightlight"

    [[control_center.shortcuts]]
    type = "notification"

    [[control_center.shortcuts]]
    type = "dark_mode"

[desktop_widgets]
schema_version = 2
widget_order = [ "desktop-widget-0000000000000002", "desktop-widget-0000000000000003" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 384.0
    box_width = 704.0
    cx = 608.0
    cy = 1088.0
    output = "DP-2"
    rotation = -0.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        background = false
        background_color = "surface"
        background_opacity = 0.80000000000000004
        background_padding = 10
        background_radius = 12
        bands = 32
        centered = true
        color_1 = "primary"
        color_2 = "secondary"
        mirrored = true
        show_when_idle = false

    [desktop_widgets.widget.desktop-widget-0000000000000003]
    box_height = 128.0
    box_width = 448.0
    cx = 480.0
    cy = 920.0
    output = "eDP-1"
    rotation = 0.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000003.settings]
        background = false
        bands = 32
        centered = true
        show_when_idle = false

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660.0

[keybinds]
down = [ "Down", "Ctrl+j" ]
left = [ "Left", "Ctrl+h" ]
right = [ "Right", "Ctrl+l" ]
up = [ "Up", "Ctrl+k" ]

[location]
auto_locate = true

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-2", "lockscreen-widget-0000000000000001", "lockscreen-widget-0000000000000002" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
    box_height = 70.0
    box_width = 400.0
    cx = 1280.0
    cy = 1104.0
    output = "DP-2"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "compact"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = false
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 1013.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "compact"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 176.0
    box_width = 368.0
    cx = 1280.0
    cy = 704.0
    output = "DP-2"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        center_text = true
        clock_style = "digital"
        color = "primary"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 96.0
    box_width = 80.0
    cx = 1280.0
    cy = 1248.0
    output = "DP-2"
    rotation = 0.0
    type = "yocraft/battery-widget:widget"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background = false
        battery = "auto"
        hide_full = false
        layout = "horizontal"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 176.0
    box_width = 240.0
    cx = 960.0
    cy = 592.0
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000003.settings]
        background_color = "primary"
        background_opacity = 0.0

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000004]
    box_height = 32.0
    box_width = 64.0
    cx = 1872.0
    cy = 24.0
    output = "eDP-1"
    rotation = 0.0
    type = "yocraft/battery-widget:widget"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000004.settings]
        background = false

[nightlight]
enabled = true
temperature_night = 4700

[notification]
layer = "overlay"

[osd.kinds]
media = false

[plugin_settings."noctalia/notes"]
notes_dir = "~/Downloads/Notes"
panel_open_near_click = false
panel_placement = "attached"
panel_position = "top_right"

[plugin_settings."noctalia/screen_recorder"]
directory = "~/Downloads/Videos/Recordings"

[plugin_settings."noctalia/wallhaven"]
browser_placement = "floating"
browser_position = "center"

[plugins]
enabled = [
    "noctalia/bongocat",
    "noctalia/wallhaven",
    "noctalia/screen_recorder",
    "oldirtty/color_picker",
    "yocraft/battery-widget"
]

[shell]
avatar_path = "/home/dominic/Downloads/Shared/Images/Profile.png"
button_borders = false
clipboard_enabled = false
corner_radius_scale = 0.0
password_style = "random"
polkit_agent = true
telemetry_enabled = true

    [shell.launcher]
    session_search = true

    [shell.panel]
    open_near_click_clipboard = true
    open_near_click_control_center = true
    open_near_click_session = true
    session_placement = "floating"
    session_position = "center"
    transparency_mode = "soft"
    wallpaper_placement = "floating"
    wallpaper_position = "center"

    [shell.screen_corners]
    size = 42

    [shell.screenshot]
    directory = "/home/dominic/Downloads/Screenshots"
    filename_pattern = "Screenshot %Y-%m-%d at %H.%M.%S"
    show_cursor = true

[theme]
builtin = "Catppuccin"
community_palette = "Vesper"
custom_palette = "catppuccin-peach"
mode = "dark"
source = "builtin"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "kcolorscheme" ]
    community_ids = []

[wallpaper]
directory = "/home/dominic/dev/wallpapers"

    [wallpaper.default]
    path = "/home/dominic/dev/wallpapers/catppuccin/waves.png"

    [wallpaper.last]
    path = "/home/dominic/dev/wallpapers/catppuccin/waves.png"

    [wallpaper.monitors.DP-2]
    path = "/home/dominic/dev/wallpapers/catppuccin/waves.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/dominic/dev/wallpapers/catppuccin/waves.png"

[weather]
refresh_minutes = 15
unit = "imperial"

[widget.battery]
enabled = true

[widget.bluetooth]
color = "primary"

[widget.brightness]
enabled = true
show_label = false

[widget.center_spacer]
enabled = true
length = 11
type = "spacer"

[widget.clipboard]
enabled = false

[widget.clock]
anchor = true
format = "{:%-I:%M %p}"

[widget.control-center]
enabled = true
glyph = "ghost-2-filled"

[widget.cpu]
show_label = false

[widget.date]
format = "{:%B %-d}"

[widget.launcher]
enabled = false

[widget.left_spacer]
enabled = true
type = "spacer"

[widget.media]
enabled = true
hide_when_no_media = true

[widget.network]
color = "secondary"
show_label = false

[widget.notes]
enabled = false
type = "noctalia/notes:notes"

[widget.privacy]
hide_inactive = true

[widget.ram]
show_label = false
stat = "ram_pct"

[widget.recorder]
type = "noctalia/screen_recorder:recorder"

[widget.recorder_2]
type = "noctalia/screen_recorder:recorder"

[widget.right_spacer]
length = 8
type = "spacer"

[widget.spacer_2]
enabled = true
type = "spacer"

[widget.tray]
drawer = true
pinned = [ "systray_141024" ]

[widget.volume]
color = "tertiary"
show_label = false

[widget.wallpaper]
enabled = false

[widget.weather]
show_condition = false

[widget.widget]
enabled = false
type = "oldirtty/color_picker:widget"
