- defaults:
    link:
      relink: true
      create: true
      force: true
    shell:
      stdin: true
      stdout: true
      stderr: true

- create: []

- clean:
    ~/:
      force: true
    ~/.config:
      recursive: true
