#!/usr/bin/env bash
set -e

# --- Vars ---
DOTFILES_REPO="git@github.com:dommcdev/dotfiles.git"
DOTFILES_DIR="$HOME/dev/dotfiles"
BREW_INSTALLED="/opt/homebrew/bin/brew"

echo -e "Starting Macbook setup...\n\n"

# Check if Homebrew is already installed
if [ ! -x "$BREW_INSTALLED" ]; then
    echo "Homebrew not found. Installing..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    eval "$(/opt/homebrew/bin/brew shellenv)"
    echo "Homebrew installation complete. You may need to restart your terminal."
else
    echo "Homebrew is already installed. Skipping installation."
fi

# Install dotfile dependencies
echo "Installing dotfile dependencies (git, python)..."
brew install git python gh

# Setup github authentication
gh auth login --web -p ssh

# Clone dotfiles
if [ ! -d "$DOTFILES_DIR" ]; then
    echo "Cloning dotfiles..."
    git clone "$DOTFILES_REPO" "$DOTFILES_DIR"
else
    echo "Dotfiles directory already exists. Skipping clone."
fi

# Run dotfiles
echo "Running dotfiles installer..."
cd "$DOTFILES_DIR" && ./install-profile mac

#Add installing xcode dev tools to beginning of mac bootstrap script
