#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_DIR="${SCRIPT_DIR}/phrases"
FONT="Delta Corps Priest 1"

mkdir -p "$OUTPUT_DIR"

# Remaining names from strings.txt (lines 6-76)
names=(
    "Applepie"
    "Drop It Like Its Hot"
    "Localhost with the Most"
    "Sir Computes Alot"
    "Desktop Biohazard"
    "Error 404 Name Not Found"
    "HAL 9000"
    "R2 D2"
    "TARDIS"
    "Skynet"
    "JARVIS"
    "Potato"
    "Hot Pocket"
    "Spaghetti Code"
    "Taco Truck"
    "Bagel Logic"
    "Leftover Pizza"
    "Sourdough"
    "Espresso"
    "Burrito"
    "Stinky Tofu"
    "It Works on My Machine"
    "The Brick"
    "Money Pit"
    "Dust Magnet"
    "Not a Virus"
    "Still Compiling"
    "Kernel Panic"
    "Works on Paper"
    "Over Engineered"
    "Load Bearing Wallpaper"
    "Sudo Make Me a Sandwich"
    "Space Heater"
    "FBI Surveillance Van"
    "It Worked Yesterday"
    "Experimental Build"
    "Held Together by Hope"
    "Overclocked Calculator"
    "Glorified Typewritter"
    "I Use Arch BTW"
    "Undefined Behavior"
    "Syntax Error"
    "Dependency Hell"
    "Not Responding"
    "Temporary Fix"
    "Dumpster Fire"
    "Nuclear Fusion"
    "Jerry Rigged"
    "Did You Try Turning It on and off Again"
    "Feature Creep"
    "Abadonware"
    "Technical Debt Collector"
    "Unstable Branch"
    "Stuck in Vim"
    "ANSI Escape Room"
    "Mouse Is Bloat"
    "512K RAM"
    "Look Ma No Mouse"
    "Buttons Sold Separately"
    "Vowels Are Extra"
    "Piped to Null"
    "Grep My Sanity"
    "Sh Happens"
    "Ncurses and Cursing"
    "Glyph Hanger"
    "TUI Much Info"
    "GPU Accelerated Text File"
    "Expensive ASCII Art"
    "Eye Candy"
    "Tiling and Toiling"
    "Cheese Grater"
)

for name in "${names[@]}"; do
    # Convert to lowercase filename with spaces as underscores
    filename=$(echo "$name" | tr '[:upper:]' '[:lower:]' | tr ' ' '_')
    output_file="${OUTPUT_DIR}/${filename}.txt"
    
    echo "Generating: ${filename}.txt"
    figlet -f "$FONT" "$name" > "$output_file"
done

echo "Done! Generated ${#names[@]} files."
