#!/usr/bin/env bash
set -e

#Note - deps installed: git, github-cli, python, openssh, base-devel

# Read in computer hostname
read -p "Please enter your computer hostname: " ARCH_HOST
echo -e "\n\n"

# Run archinstall with included configuration file. Disk selection and user creds are still manual.
curl -fsSL "https://raw.githubusercontent.com/dommcdev/bootstrap/refs/heads/main/arch/user_configuration.json" -o user_configuration.json
sed -i "s/archhostname/${ARCH_HOST}/g" user_configuration.json
archinstall --config /root/user_configuration.json

# Prepare installation for running dotfiles installer
echo -e "\n\n--- Archinstall completed successfully. Cloning dotfiles via arch-chroot ... ---\n\n"
cat << 'EOF' > /mnt/home/dominic/tmp.sh
gh auth login --web -p ssh && gh repo clone dommcdev/dotfiles /home/dominic/dev/dotfiles

command -v yay > /dev/null || (
    sudo pacman -S --noconfirm --needed base-devel
    git clone https://aur.archlinux.org/yay.git /tmp/yay
    cd /tmp/yay
    makepkg -si --noconfirm
)
EOF
arch-chroot /mnt sudo -u dominic bash home/dominic/tmp.sh
arch-chroot /mnt rm home/dominic/tmp.sh
