#!/usr/bin/env bash
set -euo pipefail

#Note - deps installed: git, github-cli, python, homebrew, make, gcc

# Detect OS
OS="unknown"
if [[ "$(uname -s)" == "Darwin" ]]; then
    OS="mac"
    BREW_BIN="/opt/homebrew/bin/brew"
elif [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
    BREW_BIN="/home/linuxbrew/.linuxbrew/bin/brew"
fi

DOTFILES_REPO="git@github.com:dommcdev/dotfiles.git"
DOTFILES_DIR="$HOME/dev/dotfiles"

echo -e "Starting configuration for $OS...\n\n"

start_sudo_loop() {
    echo -e "Please enter your password to initialize sudo keep-alive..."
    sudo -v

    while true; do
        sudo -n true
        sleep 60
        kill -0 "$$" || exit
    done 2>/dev/null &

    SUDO_LOOP_PID=$!
}

# Check if Homebrew is already installed
if [ ! -x "$BREW_BIN" ]; then
    echo "Homebrew not found. Installing..."
    NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    eval "$("$BREW_BIN" shellenv)"
    echo "Homebrew installation complete."
else
    echo "Homebrew is already installed. Skipping installation."
    eval "$("$BREW_BIN" shellenv)"
fi

# Install dotfile dependencies
echo "Installing dotfile dependencies..."
if [[ "$OS" == "ubuntu" ]]; then
    sudo apt update && sudo apt install -y python3 git gh make gcc
elif [[ "$OS" == "fedora" ]]; then
    sudo dnf install -y python3 git gh make gcc
elif [[ "$OS" == "mac" ]]; then
    brew install python3 git gh make gcc
fi

# Setup github authentication
if ! gh auth status >/dev/null 2>&1; then
    echo "Setting up GitHub auth..."
    mkdir -p ~/.ssh && chmod 700 ~/.ssh
    gh auth login --web -p ssh
    ssh-keyscan -t ed25519 github.com >> ~/.ssh/known_hosts
else
    echo "GitHub already authenticated. Skipping."
fi

# Clone dotfiles
if [ ! -d "$DOTFILES_DIR" ]; then
    echo "Cloning dotfiles..."
    git clone "$DOTFILES_REPO" "$DOTFILES_DIR"
else
    echo "Dotfiles directory already exists. Skipping clone."
fi

# Run dotfiles
echo "Running dotfiles installer..."
cd "$DOTFILES_DIR" && ./install
