#!/usr/bin/env bash
set -e

#Note - deps installed: git, github-cli, python

echo "This script will install Arch Linux on the specified drive (chosen via archinstall), as well as clone a dotfiles repo to ~/dev/dotfiles."

# Read in computer hostname
read -p "Please enter your computer hostname: " ARCH_HOST
echo -e "\n\n"

# Run archinstall with included configuration file. Disk selection and user creds are still manual.
curl -fsSL "https://raw.githubusercontent.com/dommcdev/bootstrap/refs/heads/main/arch/user_configuration.json" -o user_configuration.json
sed -i "s/archhostname/${ARCH_HOST}/g" user_configuration.json
archinstall --config /root/user_configuration.json 

# Interactively clone dotfiles
echo -e "\n\n--- Archinstall completed successfully. Cloning dotfiles via arch-chroot ... ---\n\n"
echo "gh auth login --web -p ssh && gh repo clone dommcdev/dotfiles /home/dominic/dotfiles" > /mnt/home/dominic/tmp.sh
arch-chroot /mnt sudo -u dominic bash home/dominic/tmp.sh
arch-chroot /mnt rm home/dominic/tmp.sh
