#!/usr/bin/env bash
set -euo pipefail

#Note - deps installed: git, github-cli, python, homebrew

DOTFILES_REPO="git@github.com:dommcdev/dotfiles.git"
DOTFILES_DIR="$HOME/dev/dotfiles"
BREW_BIN="/home/linuxbrew/.linuxbrew/bin/brew

echo -e "Starting Ubuntu configuration...\n\n"

# Check if Homebrew is already installed
if [ ! -x "$BREW_BIN" ]; then
    echo "Homebrew not found. Installing..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    eval "$("$BREW_BIN" shellenv)"
    echo "Homebrew installation complete."
else
    echo "Homebrew is already installed. Skipping installation."
    eval "$("$BREW_BIN" shellenv)"
fi

# Install dotfile dependencies
echo "Installing dotfile dependencies (git, python)..."
sudo apt install -y python3 git gh

# Setup github authentication
if ! gh auth status >/dev/null 2>&1; then
    echo "Setting up GitHub auth..."
    gh auth login --web -p ssh
else
    echo "GitHub already authenticated. Skipping."
fi

# Clone dotfiles
if [ ! -d "$DOTFILES_DIR" ]; then
    echo "Cloning dotfiles..."
    git clone "$DOTFILES_REPO" "$DOTFILES_DIR"
else
    echo "Dotfiles directory already exists. Skipping clone."
fi

# Run dotfiles
echo "Running dotfiles installer..."
cd "$DOTFILES_DIR" && ./install
