root: "{{ playbook_dir }}/.."
home: "{{ ansible_env.HOME }}"
user: "{{ ansible_user_id }}"

brew_environment:
  PATH: "/opt/homebrew/bin:/usr/local/bin:{{ ansible_env.PATH }}"

os_id: "{{ 'mac' if ansible_system == 'Darwin' else (ansible_distribution | lower) }}"
is_arch: "{{ os_id in ['arch', 'archlinux'] }}"
is_ubuntu: "{{ os_id == 'ubuntu' }}"
is_fedora: "{{ os_id == 'fedora' }}"
is_macos: "{{ ansible_system == 'Darwin' }}"
is_linux: "{{ ansible_system == 'Linux' }}"
is_desktop: "{{ 'desktops' in group_names or 'custom' in group_names }}"
is_custom: "{{ 'custom' in group_names }}"
