root: "{{ playbook_dir }}/.."
home: "{{ ansible_env.HOME }}"
user: "{{ ansible_user_id }}"

brew_environment:
  PATH: "/opt/homebrew/bin:/home/linuxbrew/.linuxbrew/bin"

is_arch: "{{ (ansible_distribution | lower) in ['arch', 'archlinux', 'cachyos'] }}"
is_ubuntu: "{{ (ansible_distribution | lower) in ['ubuntu', 'debian', 'linuxmint'] }}"
is_fedora: "{{ (ansible_distribution | lower) == 'fedora' }}"
is_macos: "{{ ansible_system == 'Darwin' }}"
is_linux: "{{ ansible_system == 'Linux' }}"
is_desktop: "{{ 'desktops' in group_names }}"
is_custom: "{{ 'custom' in group_names }}"
is_server: "{{ 'servers' in group_names }}"
