# Apply to every keyboard
[ids]
*

[main]
# Caps is ctrl when held, esc when tapped
capslock = overload(control, esc)

# Map physical alt to software meta
leftalt = leftmeta
rightalt = rightmeta

# Map physical meta to software alt
leftmeta = leftalt
rightmeta = rightalt

# Boths shifts together toggle capslock
leftshift+rightshift = capslock

# Emulate arrow keys with alt + h/j/k/l
[alt]
h = left
j = down
k = up
l = right

[alt+shift]
h = M-S-h
j = M-S-j
k = M-S-k
l = M-S-l

[alt+control]
h = M-C-h
j = M-C-j
k = M-C-k
l = M-C-l

[alt+meta]
h = M-A-h
j = M-A-j
k = M-A-k
l = M-A-l
