# Apply to every keyboard
[ids]
*

[main]
# Caps is ctrl when held, esc when tapped
capslock = overload(control, esc)

# Map physical alt to software meta
leftalt = leftmeta
rightalt = rightmeta

# Map physical meta to software alt
leftmeta = leftalt
rightmeta = rightalt

# Boths shifts together toggle capslock
leftshift+rightshift = capslock

# Emulate arrow keys with meta + h/j/k/l
[meta]
h = left
j = down
k = up
l = right

[meta+shift]
h = M-S-h
j = M-S-j
k = M-S-k
l = M-S-l

[meta+control]
h = M-C-h
j = M-C-j
k = M-C-k
l = M-C-l

[meta+alt]
h = M-A-h
j = M-A-j
k = M-A-k
l = M-A-l
