# Apply to every keyboard
[ids]
*

[main]
# Caps is ctrl when held, esc when tapped
capslock = overload(control, esc)

# Map both physical alt keys to a custom meta layer
leftalt = layer(custommeta)
rightalt = layer(custommeta)

# Map both physical meta keys to alt
leftmeta = leftalt
rightmeta = rightalt

# Boths shifts together toggle capslock
leftshift+rightshift = capslock

# This is a custom layer. The :M means that it inherits all default control keybindings.
[custommeta:M]
h = left
j = down
k = up
l = right
