- name: Install terminal packages
  vars:
    pkgs:
      Archlinux:
        - ouch
        - unzip
        - 7zip
        - unarchiver
        - unrar
        - wget
        - curl
        - ffmpeg
        - fd
        - ripgrep
        - poppler
        - zoxide
        - imagemagick
        - chafa
        - resvg
        - ncdu
        - fzf
        - trash-cli
        - tldr
        - whois
        - eza
        - jq
        - less
        - yt-dlp
        - gum
        - git-delta
        - difftastic
        - nmap
        - bind
        - lazygit
        - acpi
        - caligula
        - dust
        - glow
        - playerctl
        - duf
        - figlet
        - man-db
        - man-pages
        - bc
        - id3v2
      Debian:
        - unzip
        - 7zip
        - unar
        - unrar
        - trash-cli
        - wget
        - ffmpeg
        - fd-find
        - ripgrep
        - poppler-utils
        - zoxide
        - imagemagick
        - ghostscript
        - chafa
        - ncdu
        - eza
        - jq
        - less
        - git-delta
        - nmap
        - bind9-dnsutils
        - playerctl
        - duf
        - figlet
        - bc
        - id3v2
      RedHat:
        - unzip
        - 7zip
        - unar
        - unrar
        - trash-cli
        - wget
        - ffmpeg
        - fd-find
        - ripgrep
        - poppler-utils
        - zoxide
        - ImageMagick
        - ghostscript
        - chafa
        - ncdu
        - eza
        - jq
        - less
        - git-delta
        - nmap
        - bind-utils
        - playerctl
        - duf
        - figlet
        - bc
        - id3v2
    brew_pkgs:
      - fzf
      - yt-dlp
      - tlrc
      - resvg
      - gum
      - ouch
      - dust
      - glow
      - difftastic
      - caligula
    macos_brew_pkgs:
      - ouch
      - unzip
      - 7zip
      - unar
      - ffmpeg
      - wget
      - fd
      - ripgrep
      - poppler
      - zoxide
      - imagemagick
      - ghostscript
      - chafa
      - resvg
      - ncdu
      - fzf
      - tlrc
      - eza
      - jq
      - less
      - yt-dlp
      - gum
      - git-delta
      - nmap
      - bind
      - dust
      - glow
      - duf
      - figlet
      - difftastic
      - bc
      - id3v2
      - caligula
  block:
    - name: Install native terminal packages
      ansible.builtin.package:
        name: "{{ pkgs[ansible_facts['os_family']] }}"
        state: present
      become: true
      when: ansible_facts['os_family'] in pkgs

    - name: Install terminal Homebrew packages on Linux
      community.general.homebrew:
        name: "{{ brew_pkgs }}"
        state: present
        update_homebrew: false
      when: is_debian or is_redhat

    - name: Install terminal Homebrew packages on macOS
      community.general.homebrew:
        name: "{{ macos_brew_pkgs }}"
        state: present
        update_homebrew: false
      when: is_macos
