- name: Install Docker
  block:
    - name: Install Docker packages on Arch
      ansible.builtin.package:
        name:
          - docker
          - docker-compose
          - lazydocker
        state: present
      become: true
      when: is_arch

    - name: Install Docker packages on Ubuntu and Fedora
      become: true
      when: is_debian or is_redhat
      block:
        - name: Download Docker installer
          ansible.builtin.get_url:
            url: https://get.docker.com
            dest: /tmp/get-docker.sh
            mode: "0755"

        - name: Run Docker installer
          ansible.builtin.command: /tmp/get-docker.sh
          args:
            creates: /usr/bin/docker

        - name: Install lazydocker
          community.general.homebrew:
            name: lazydocker
            state: present
            update_homebrew: false
          environment: "{{ brew_environment }}"

    - name: Install Docker with Homebrew on macOS
      community.general.homebrew:
        name:
          - docker
          - docker-compose
          - lazydocker
        state: present
        update_homebrew: false
      environment: "{{ brew_environment }}"
      when: is_macos

- name: Configure Docker on Linux
  become: true
  when: is_linux
  block:
    - name: Create Docker configuration directory
      ansible.builtin.file:
        path: /etc/docker
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Configure Docker daemon
      ansible.builtin.copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "ip-forward-no-drop": true,
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "10m",
              "max-file": "5"
            }
          }
        owner: root
        group: root
        mode: "0644"
      register: docker_config

    - name: Enable/restart Docker service on headless machines
      ansible.builtin.systemd_service:
        name: docker.service
        enabled: true
        state: "{{ 'restarted' if docker_config.changed else 'started' }}"
      when: is_headless

    - name: Enable Docker socket on desktop machines
      ansible.builtin.systemd_service:
        name: docker.socket
        enabled: true
        state: started
      when: not is_headless

    - name: Disable Docker service on desktop machines
      ansible.builtin.systemd_service:
        name: docker.service
        enabled: false
      when: not is_headless

    - name: Add user to Docker group
      ansible.builtin.user:
        name: "{{ user }}"
        groups: docker
        append: true
