- name: Install fonts
  vars:
    pkgs:
      Archlinux:
        - noto-fonts
        - noto-fonts-cjk
        - noto-fonts-emoji
        - noto-fonts-extra
        - ttf-jetbrains-mono-nerd
  block:
    - name: Install native font packages
      ansible.builtin.package:
        name: "{{ pkgs[ansible_facts['os_family']] }}"
        state: present
      become: true
      when: ansible_facts['os_family'] in pkgs

    - name: Create local font directory
      ansible.builtin.file:
        path: "{{ home }}/.local/share/fonts"
        state: directory
        mode: "0755"
      when: is_debian or is_redhat

    - name: Install JetBrains Mono Nerd Font on Debian and Red Hat
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.tar.xz
        dest: "{{ home }}/.local/share/fonts"
        remote_src: true
        creates: "{{ home }}/.local/share/fonts/JetBrainsMonoNerdFont-Regular.ttf"
      register: jetbrains_mono_nerd_font
      when: is_debian or is_redhat

    - name: Install JetBrains Mono Nerd Font on macOS
      community.general.homebrew_cask:
        name: font-jetbrains-mono-nerd-font
        state: present
        update_homebrew: false
      when: is_macos

- name: Configure fonts on Linux
  when: is_linux
  block:
    - name: Create fontconfig directory
      ansible.builtin.file:
        path: "{{ home }}/.config/fontconfig"
        state: directory
        mode: "0755"

    - name: Link fontconfig
      ansible.builtin.file:
        src: "{{ root }}/styling/fonts/fonts.conf"
        dest: "{{ home }}/.config/fontconfig/fonts.conf"
        state: link
        force: true
      register: fontconfig

- name: Configure desktop font
  ansible.builtin.command: "gsettings set org.gnome.desktop.interface font-name 'Adwaita Sans 11'"
  changed_when: false
  when: is_linux and is_managed_desktop

- name: Refresh font cache
  ansible.builtin.command: fc-cache -f
  changed_when: true
  when:
    - is_linux
    - (jetbrains_mono_nerd_font is not skipped and jetbrains_mono_nerd_font is changed) or fontconfig is changed
#
# Nota bene
# fc-match [serif|sans-serif|monospace etc]
# fc-cache -rv
