- name: Install Ghostty
  block:
    - name: Install Ghostty on Arch
      ansible.builtin.package:
        name:
          - ghostty
          - ttf-jetbrains-mono-nerd
        state: present
      become: true
      when: is_arch

    - name: Enable Ghostty COPR on Fedora
      community.general.copr:
        name: scottames/ghostty
        state: enabled
      become: true
      when: is_redhat

    - name: Install Ghostty on Fedora
      ansible.builtin.package:
        name: ghostty
        state: present
      become: true
      when: is_redhat

    - name: Install Ghostty on Ubuntu
      ansible.builtin.shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/mkasberg/ghostty-ubuntu/HEAD/install.sh)"
      args:
        creates: /usr/bin/ghostty
      become: true
      when: is_debian

    - name: Install Ghostty and font on macOS
      community.general.homebrew_cask:
        name:
          - ghostty
          - font-jetbrains-mono-nerd-font
        state: present
        update_homebrew: false
      environment: "{{ brew_environment }}"
      when: is_macos

- name: Configure Ghostty
  block:
    - name: Create config directory
      ansible.builtin.file:
        path: "{{ home }}/.config/ghostty"
        state: directory
        mode: "0755"

    - name: Link config
      ansible.builtin.file:
        src: "{{ root }}/ghostty/config"
        dest: "{{ home }}/.config/ghostty/config"
        state: link
        force: true

- name: Configure Ghostty on Linux
  when: is_linux
  block:
    - name: Enable Ghostty user service
      ansible.builtin.systemd_service:
        name: app-com.mitchellh.ghostty.service
        enabled: true
        scope: user

    - name: Set Ghostty as default xdg terminal
      ansible.builtin.copy:
        dest: "{{ home }}/.config/xdg-terminals.list"
        mode: "0644"
        content: |
          # Terminal emulator preference order for xdg-terminal-exec
          com.mitchellh.ghostty.desktop
