- name: Install Ghostty
  vars:
    pkgs:
      Archlinux:
        - ghostty
        - ghostty-nautilus
        - ttf-jetbrains-mono-nerd
      Debian:
        - ghostty
      RedHat:
        - ghostty
  block:
    - name: Enable Ghostty COPR on Fedora
      community.general.copr:
        name: scottames/ghostty
        state: enabled
      become: true
      when: is_redhat

    - name: Install Ghostty on Linux
      ansible.builtin.package:
        name: "{{ pkgs[ansible_facts['os_family']] }}"
        state: present
      become: true
      when: ansible_facts['os_family'] in pkgs

    - name: Install Ghostty and font on macOS
      community.general.homebrew_cask:
        name:
          - ghostty
          - font-jetbrains-mono-nerd-font
        state: present
        update_homebrew: false
      when: is_macos

- name: Configure Ghostty
  block:
    - name: Create config directory
      ansible.builtin.file:
        path: "{{ home }}/.config/ghostty"
        state: directory
        mode: "0755"

    - name: Link config
      ansible.builtin.file:
        src: "{{ root }}/ghostty/config"
        dest: "{{ home }}/.config/ghostty/config"
        state: link
        force: true

- name: Linux-specific Ghostty config
  when: is_linux
  block:
    - name: Enable Ghostty user service
      ansible.builtin.systemd_service:
        name: app-com.mitchellh.ghostty.service
        enabled: true
        scope: user

    - name: Set Ghostty as default xdg terminal
      ansible.builtin.copy:
        dest: "{{ home }}/.config/xdg-terminals.list"
        mode: "0644"
        content: |
          # Terminal emulator preference order for xdg-terminal-exec
          com.mitchellh.ghostty.desktop
