- name: Link Git config files
  block:
    - name: Ensure config directory exists
      ansible.builtin.file:
        path: "{{ home }}/.config/git"
        state: directory
        mode: "0755"

    - name: Link config files
      ansible.builtin.file:
        src: "{{ root }}/git/{{ item }}"
        dest: "{{ home }}/.config/git/{{ item }}"
        state: link
        force: true
      loop:
        - config
        - ignore

- name: Install Git packages
  ansible.builtin.package:
    name: "{{ pkgs[ansible_facts['os_family']] }}"
    state: present
  become: true
  when: ansible_facts['os_family'] in pkgs
  vars:
    pkgs:
      Archlinux:
        - git
        - github-cli
      Debian:
        - git
        - gh
      RedHat:
        - git
        - gh

- name: Install Git packages on macOS
  community.general.homebrew:
    name:
      - git
      - gh
    state: present
    update_homebrew: false
  environment: "{{ brew_environment }}"
  when: is_macos
