- name: Configure Hyprland
  when: is_arch and is_managed_desktop
  block:
    - name: Create Hyprland and UWSM config directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ home }}/.config/hypr"
        - "{{ home }}/.config/uwsm"

    - name: Link Hyprland configs except runtime variants
      ansible.builtin.file:
        src: "{{ item }}"
        dest: "{{ home }}/.config/hypr/{{ item | basename }}"
        state: link
        force: true
      loop: "{{ lookup('ansible.builtin.fileglob', root + '/hypr/*', wantlist=True) | reject('match', '.*/uwsm$') | list }}"

    - name: Link UWSM configs
      ansible.builtin.file:
        src: "{{ item }}"
        dest: "{{ home }}/.config/uwsm/{{ item | basename }}"
        state: link
        force: true
      loop: "{{ lookup('ansible.builtin.fileglob', root + '/hypr/uwsm/*', wantlist=True) }}"

    - name: Install Hyprland packages
      ansible.builtin.package:
        name:
          - uwsm
          - libnewt
          - xdg-desktop-portal-hyprland
          - xdg-desktop-portal-gtk
          - hyprland
          - satty
          - hyprland-qt-support
        state: present
      become: true

    - name: Let Hyprland handle the power button
      ansible.builtin.lineinfile:
        path: /etc/systemd/logind.conf
        regexp: "^#?HandlePowerKey=.*$"
        line: "HandlePowerKey=ignore"
      become: true
