- name: Install keyd package
  block:
    - name: Enable keyd COPR on Fedora
      community.general.copr:
        name: alternateved/keyd
        state: enabled
      become: true
      when: is_redhat

    - name: Install keyd
      ansible.builtin.package:
        name: keyd
        state: present
      become: true

- name: Configure keyd on Linux
  become: true
  block:
    - name: Create keyd config directory
      ansible.builtin.file:
        path: /etc/keyd
        state: directory
        mode: "0755"

    - name: Copy keyd default config
      ansible.builtin.copy:
        src: "{{ root }}/keyd/default.conf"
        dest: /etc/keyd/default.conf
        mode: "0644"
        remote_src: true
      register: keyd_config

    - name: Enable keyd
      ansible.builtin.systemd_service:
        name: keyd.service
        daemon_reload: true
        enabled: true
        state: "{{ 'restarted' if keyd_config.changed else 'started' }}"

    - name: Create libinput config directory
      ansible.builtin.file:
        path: /etc/libinput
        state: directory
        mode: "0755"

    - name: Mark keyd virtual keyboard as internal
      ansible.builtin.blockinfile:
        path: /etc/libinput/local-overrides.quirks
        create: true
        mode: "0644"
        marker: "# {mark} ANSIBLE DOTFILES KEYD QUIRK"
        block: |
          [Serial Keyboards]

          MatchUdevType=keyboard
          MatchName=*keyd*keyboard
          AttrKeyboardIntegration=internal

# Useful commands
# libinput quirks validate --data-dir /etc/libinput
# libinput list-devices
# libinput debug-events
