- name: Install keyd package
  block:
    - name: Enable keyd COPR on Fedora
      community.general.copr:
        name: alternateved/keyd
        state: enabled
      become: true
      when: is_fedora

    - name: Install keyd
      ansible.builtin.package:
        name: keyd
        state: present
      become: true

- name: Configure keyd on Linux
  become: true
  block:
    - name: Create keyd config directory
      ansible.builtin.file:
        path: /etc/keyd
        state: directory
        mode: "0755"

    - name: Copy keyd config
      ansible.builtin.copy:
        dest: /etc/keyd/default.conf
        mode: "0644"
        content: |
          # Apply to every keyboard
          [ids]
          *

          [main]
          # Caps is ctrl when held, esc when tapped
          capslock = overload(control, esc)

          # Map physical alt to software meta
          leftalt = leftmeta
          rightalt = rightmeta

          # Map physical meta to software alt
          leftmeta = leftalt
          rightmeta = rightalt

          # Boths shifts together toggle capslock
          leftshift+rightshift = capslock

          # Emulate arrow keys with alt + h/j/k/l
          [alt]
          h = left
          j = down
          k = up
          l = right

          [alt+shift]
          h = M-S-h
          j = M-S-j
          k = M-S-k
          l = M-S-l

          [alt+control]
          h = M-C-h
          j = M-C-j
          k = M-C-k
          l = M-C-l

          [alt+meta]
          h = M-A-h
          j = M-A-j
          k = M-A-k
          l = M-A-l
      register: keyd_config

    - name: Enable/restart keyd
      ansible.builtin.systemd_service:
        name: keyd.service
        enabled: true
        state: "{{ 'restarted' if keyd_config.changed else 'started' }}"

    - name: Create libinput config directory
      ansible.builtin.file:
        path: /etc/libinput
        state: directory
        mode: "0755"

    - name: Mark keyd virtual keyboard as internal
      ansible.builtin.blockinfile:
        path: /etc/libinput/local-overrides.quirks
        create: true
        mode: "0644"
        marker: "# {mark} ANSIBLE DOTFILES KEYD QUIRK"
        block: |
          [Serial Keyboards]

          MatchUdevType=keyboard
          MatchName=*keyd*keyboard
          AttrKeyboardIntegration=internal

# Useful commands
# libinput quirks validate --data-dir /etc/libinput
# libinput list-devices
# libinput debug-events
# Note: On Ubuntu the binary is keyd.rvaiya
