- name: Install virtualization packages
  ansible.builtin.package:
    name: "{{ pkgs[ansible_facts['os_family']] }}"
    state: present
  become: true
  when: ansible_facts['os_family'] in pkgs
  vars:
    pkgs:
      Archlinux:
        - dnsmasq
        - libvirt
        - qemu-desktop
        - virt-manager
        - virt-viewer
      Debian:
        - dnsmasq-base
        - libvirt-clients
        - libvirt-daemon-config-network
        - libvirt-daemon-system
        - qemu-system-x86
        - virt-manager
        - virt-viewer
      RedHat:
        - dnsmasq
        - libvirt-client
        - libvirt-daemon-config-network
        - libvirt-daemon-kvm
        - qemu-kvm
        - virt-install
        - virt-manager
        - virt-viewer

- name: Configure virtualization
  become: true
  block:
    - name: Enable libvirtd
      ansible.builtin.systemd_service:
        name: libvirtd.service
        enabled: true
        state: started

    - name: Add user to libvirt group
      ansible.builtin.user:
        name: "{{ user }}"
        groups: libvirt
        append: true

- name: Ensure default network autostarts on physical machines
  community.libvirt.virt_net:
    name: default
    autostart: true
  when: ansible_facts['virtualization_role'] == 'host'
#
# sudo virsh net-list --all
