- name: Install Noctalia packages
  vars:
    pkgs:
      Archlinux:
        - noctalia
        - noctalia-greeter
        - greetd
        - accountsservice
        - gpu-screen-recorder
  ansible.builtin.package:
    name: "{{ pkgs[ansible_facts['os_family']] }}"
    state: present
  become: true
  when: ansible_facts['os_family'] in pkgs

- name: Configure greetd
  block:
    - name: Copy config
      ansible.builtin.copy:
        dest: /etc/greetd/config.toml
        owner: root
        group: root
        mode: "0644"
        content: |
          [terminal]
          vt=1

          [default_session]
          command = "/usr/bin/noctalia-greeter-session"
          user = "greeter"
      become: true
      register: greetd_config

    - name: Configure PAM
      ansible.builtin.copy:
        dest: /etc/pam.d/greetd
        owner: root
        group: root
        mode: "0644"
        content: |
          auth       required     pam_securetty.so
          auth       requisite    pam_nologin.so
          auth       include      system-local-login
          auth       optional     pam_gnome_keyring.so
          account    include      system-local-login
          session    include      system-local-login
          session    optional     pam_gnome_keyring.so auto_start
      become: true
      register: greetd_pam_config

- name: Configure noctalia-greeter
  ansible.builtin.copy:
    dest: /var/lib/noctalia-greeter/greeter.toml
    owner: greeter
    group: greeter
    mode: "0644"
    content: |
      [user]
      default = "{{ user }}"

      [appearance]
      hide_logo = true
      password_style = "random"

      [idle]
      timeout = 600

      [cursor]
      theme = "breeze_cursors"
      size = 24

      [auth]
      # For fprintd
      allow_empty_password = true
  become: true
  register: noctalia_greeter_config

  # DO NOT restart greetd.service, or else your session will go down with it.
- name: Enable greetd
  ansible.builtin.systemd_service:
    name: greetd.service
    enabled: true
    state: started
  become: true

- name: Configure Noctalia
  block:
    - name: Create config directory
      ansible.builtin.file:
        path: "{{ home }}/.config/noctalia"
        state: directory
        mode: "0755"

    - name: Link config
      ansible.builtin.file:
        src: "{{ root }}/noctalia/noctalia-config.toml"
        dest: "{{ home }}/.config/noctalia/noctalia-config.toml"
        state: link
        force: true
# To restart noctalia...
# pkill noctalia && hyprctl dispatch "hl.dsp.exec_cmd('noctalia')"

# TODO Add Debian and Fedora support
# TODO Set fractional scaling per-device?
