- name: Install SSH package
  block:
    - name: Install on Linux
      ansible.builtin.package:
        name: "{{ 'openssh' if is_arch else 'openssh-server' }}"
        state: present
      become: true
      when: is_linux

    - name: Install on macOS via homebrew
      community.general.homebrew:
        name: openssh
        state: present
        update_homebrew: false
      environment: "{{ brew_environment }}"
      when: is_macos

- name: Ensure SSH config directory exists
  ansible.builtin.file:
    path: "{{ home }}/.ssh"
    state: directory
    mode: "0700"

- name: Link SSH config
  ansible.builtin.file:
    src: "{{ root }}/ssh/config"
    dest: "{{ home }}/.ssh/config"
    state: link
    force: true

- name: Configure SSH daemon
  block:
    - name: Disable password authentication
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PasswordAuthentication .*$"
        line: "PasswordAuthentication no"
      become: true
      register: ssh_pass_auth
      when: is_linux

    - name: Disable root login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PermitRootLogin .*$"
        line: "PermitRootLogin no"
      become: true
      register: ssh_root_login
      when: is_linux

- name: Enable/restart SSH
  ansible.builtin.systemd_service:
    name: "{{ 'ssh' if is_debian else 'sshd' }}.service"
    enabled: true
    state: "{{ 'restarted' if ssh_pass_auth.changed or ssh_root_login.changed else 'started' }}"
  become: true
  when: is_linux
