- name: Install Syncthing package
  block:
    - name: Install on Linux
      ansible.builtin.package:
        name: syncthing
        state: present
      become: true
      when: is_linux

    - name: Install on macOS via homebrew
      community.general.homebrew:
        name: syncthing
        state: present
        update_homebrew: false
      when: is_macos

- name: Enable Syncthing
  block:
    - name: Enable as a user service # Starts on graphical/ssh login
      ansible.builtin.systemd_service:
        name: syncthing.service
        enabled: true
        state: started
        scope: user
      when: not is_headless

    - name: Enable as a system service # Starts at boot rather than graphical/ssh login
      ansible.builtin.systemd_service:
        name: "syncthing@{{ user }}.service"
        enabled: true
        state: started
      become: true
      when: is_headless
#
#
# Instructions for device setup
# I use the hub-and-spoke approach. All devices sync to chocobo (and not to each other).
# First, set up chocobo. Change the GUI listen address to <machine.ip>:8384 to allow
# other devices to access it. Set a GUI password since this will be available to the
# local network. In settings/connections, turn off everything but local discovery
# (don't think we need any of them). Grab the ID string.
# Then, set up your other devices. No need to modify GUI settings or add a GUI
# password here. Change connection settings as above, click add remote device, and
# enter the ID string. Under advanced settings, change the address to
# tcp://chocobo:22000 rather than dynamic.
# Over on chocobo hit accept. No need to change the address here though (it can stay dynamic).
#
# I think you can initiate a folder from either device. Create a folder on one device
# with the correct path for that machine, then share it with chocobo or, when on
# chocobo, with everyone. Accept it on the other devices and change the path if needed.
