- name: Install Tailscale on Arch
  ansible.builtin.package:
    name: tailscale
    state: present
  become: true
  when: is_arch

- name: Install Tailscale on Ubuntu and Fedora
  when: is_ubuntu or is_fedora
  block:
    - name: Download installer
      ansible.builtin.get_url:
        url: https://tailscale.com/install.sh
        dest: /tmp/tailscale_install.sh
        mode: "0755"

    - name: Run installer
      ansible.builtin.command: /tmp/tailscale_install.sh
      args:
        creates: /usr/bin/tailscale
      become: true

- name: Install Tailscale app on macOS
  community.general.homebrew_cask:
    name: tailscale-app
    state: present
    update_homebrew: false
  when: is_macos

- name: Enable tailscaled
  ansible.builtin.systemd_service:
    name: tailscaled.service
    enabled: true
    state: started
  become: true
  when: is_linux

- name: Start and authenticate Tailscale
  ansible.builtin.command:
    argv:
      - tailscale
      - up
      - "--auth-key={{ prepared_tailscale_auth_key }}"
      - --reset
  become: true
  changed_when: false
  no_log: true
  when:
    - is_linux
    - prepared_tailscale_auth_key is defined
    - prepared_tailscale_auth_key | length > 0

- name: Configure Tailscale options
  ansible.builtin.command:
    argv:
      - tailscale
      - set
      - --ssh
      - "--operator={{ user }}"
  become: true
  changed_when: false
  when: is_linux
#
#
# Subnet router note: Using --accept-routes DOES NOT WORK when on the same network as
# the subnet router WHEN that subnet router is off. Turn it on or off with
# tailscale set --accept-routes=[true|false]
#
# To turn exit node on, do
#   tailscale set --exit-node=[name]
# To turn off, do
#   tailscale set --exit-node=
#
# tailscale wait (tailscale-online.target) might prove useful if we ever run into timing issues
