- name: Install TUI packages
  block:
    - name: Install native TUI packages
      ansible.builtin.package:
        name: "{{ pkgs[ansible_facts['os_family']] }}"
        state: present
      become: true
      when: ansible_facts['os_family'] in pkgs

    - name: Install TUI Homebrew packages on Linux
      community.general.homebrew:
        name: "{{ brew_pkgs }}"
        state: present
        update_homebrew: false
      when: is_debian or is_redhat

    - name: Install TUI Homebrew packages on macOS
      community.general.homebrew:
        name: "{{ macos_brew_pkgs }}"
        state: present
        update_homebrew: false
      when: is_macos
  vars:
    pkgs:
      Archlinux:
        - bat
        - beets
        - btop
        - fastfetch
        - libqalculate
        - starship
      Debian:
        - qalc
      RedHat:
        - libqalculate
    brew_pkgs:
      - bat
      - beets
      - btop
      - fastfetch
      - starship
    macos_brew_pkgs:
      - bat
      - beets
      - btop
      - fastfetch
      - libqalculate
      - starship

# NOTE: Ubuntu/Fedora are missing wlctl, bluetui, and wiremix. Might be able to grab from crates.io or smth
- name: Install additional desktop-only TUI packages
  when: is_managed_desktop
  block:
    - name: Install on Linux
      ansible.builtin.package:
        name: "{{ pkgs[ansible_facts['os_family']] }}"
        state: present
      become: true
      when: ansible_facts['os_family'] in pkgs

    - name: Install wlctl from AUR
      kewlfft.aur.aur:
        name: wlctl-bin
        state: present
      when: is_arch

    - name: Install on macOS
      community.general.homebrew:
        name: "{{ macos_brew_pkgs }}"
        state: present
        update_homebrew: false
      when: is_macos
  vars:
    pkgs:
      Archlinux:
        - cava
        - bluetui
        - wiremix
      Debian:
        - blueman
        - pavucontrol
      RedHat:
        - blueman
        - pavucontrol
    macos_brew_pkgs:
      - cava

- name: Configure TUI applications
  block:
    - name: Ensure config dirs exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ home }}/.config/beets"
        - "{{ home }}/.config/qalculate"
        - "{{ home }}/.config/cava"
        - "{{ home }}/.config/fastfetch"

    - name: Link bat config (DIR)
      ansible.builtin.file:
        src: "{{ root }}/tui/bat"
        dest: "{{ home }}/.config/bat"
        state: link
        force: true

    - name: Link beets config (FILE)
      ansible.builtin.file:
        src: "{{ root }}/tui/beets/config.yaml"
        dest: "{{ home }}/.config/beets/config.yaml"
        state: link
        force: true

    - name: Link btop config (DIR)
      ansible.builtin.file:
        src: "{{ root }}/tui/btop"
        dest: "{{ home }}/.config/btop"
        state: link
        force: true

    - name: Link cava config (FILE)
      ansible.builtin.file:
        src: "{{ root }}/tui/cava/config"
        dest: "{{ home }}/.config/cava/config"
        state: link
        force: true

    - name: Link fastfetch config (FILES)
      ansible.builtin.file:
        src: "{{ root }}/tui/fastfetch/{{ item }}"
        dest: "{{ home }}/.config/fastfetch/{{ item }}"
        state: link
        force: true
      loop:
        - config.jsonc
        - full.jsonc

    - name: Link qalculate config (FILE)
      ansible.builtin.file:
        src: "{{ root }}/tui/qalc/qalc.cfg"
        dest: "{{ home }}/.config/qalculate/qalc.cfg"
        state: link
        force: true

    - name: Link Starship config (FILE)
      ansible.builtin.file:
        src: "{{ root }}/tui/starship/starship.toml"
        dest: "{{ home }}/.config/starship.toml"
        state: link
        force: true

- name: Build bat cache
  ansible.builtin.command: bat cache --build
  changed_when: false
