- name: Install Vicinae
  block:
    - name: Install Vicinae on Arch
      kewlfft.aur.aur:
        name: vicinae-bin
        state: present
      when: is_arch

    - name: Install Vicinae on Fedora
      block:
        - name: Enable COPR
          community.general.copr:
            name: quadratech188/vicinae
            state: enabled
          become: true
          when: is_fedora

        - name: Install package
          ansible.builtin.dnf:
            name: vicinae
            state: present
          become: true
          when: is_fedora

    - name: Install Vicinae on macOS
      community.general.homebrew_cask:
        name: vicinae
        state: present
        update_homebrew: false
      when: is_macos

- name: Configure Vicinae
  block:
    - name: Create config directory
      ansible.builtin.file:
        path: "{{ home }}/.config/vicinae"
        state: directory
        mode: "0755"

    - name: Link settings
      ansible.builtin.file:
        src: "{{ root }}/vicinae/settings.json"
        dest: "{{ home }}/.config/vicinae/settings.json"
        state: link
        force: true
      register: vicinae_settings

- name: Enable/restart Vicinae
  ansible.builtin.systemd_service:
    name: vicinae.service
    enabled: true
    state: "{{ 'restarted' if vicinae_settings.changed else 'started' }}"
    scope: user
  when: is_linux
