- name: Install zsh
  ansible.builtin.package:
    name: zsh
    state: present
  become: true
  when: is_linux

- name: Link zsh config
  block:
    - name: Ensure config directory exists
      ansible.builtin.file:
        path: "{{ home }}/.config/zsh"
        state: directory
        mode: "0755"

    - name: Link zshrc
      ansible.builtin.file:
        src: "{{ root }}/zsh/zshrc"
        dest: "{{ home }}/.config/zsh/.zshrc"
        state: link
        force: true

    - name: Link macOS zprofile
      ansible.builtin.file:
        src: "{{ root }}/zsh/zprofile-mac"
        dest: "{{ home }}/.config/zsh/.zprofile"
        state: link
        force: true
      when: is_macos

    - name: Link zshenv
      ansible.builtin.file:
        src: "{{ root }}/zsh/zshenv"
        dest: "{{ home }}/.zshenv"
        state: link
        force: true

- name: Set zsh as login shell
  ansible.builtin.user:
    name: "{{ user }}"
    shell: /usr/bin/zsh
  become: true
  when: is_linux
