- name: Install Docker packages on Arch
  ansible.builtin.package:
    name:
      - docker
      - docker-compose
      - lazydocker
    state: present
  become: true
  when: is_arch

- name: Install Docker on Ubuntu and Fedora
  ansible.builtin.shell: |
    curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
    sh /tmp/get-docker.sh
  args:
    creates: /usr/bin/docker
  become: true
  when: is_ubuntu or is_fedora

- name: Install lazydocker with Homebrew on Ubuntu and Fedora
  community.general.homebrew:
    name: lazydocker
    state: present
    update_homebrew: false
  environment: "{{ brew_environment }}"
  when: is_ubuntu or is_fedora

- name: Install Docker with Homebrew on macOS
  community.general.homebrew:
    name:
      - docker
      - docker-compose
      - lazydocker
    state: present
    update_homebrew: false
  environment: "{{ brew_environment }}"
  when: is_macos

- name: Enable Docker on Linux
  ansible.builtin.systemd_service:
    name: docker.service
    enabled: true
    state: started
  become: true
  when: is_linux

- name: Add user to Docker group
  ansible.builtin.user:
    name: "{{ user }}"
    groups: docker
    append: true
  become: true
  when: is_linux
