- name: Link Dunst config
  ansible.builtin.file:
    src: "{{ root }}/dunst"
    dest: "{{ home }}/.config/dunst"
    state: link
    force: true

- name: Install Dunst
  ansible.builtin.package:
    name:
      - dunst
      - libnotify
    state: present
  become: true
