- name: Ensure git config directory exists
  ansible.builtin.file:
    path: "{{ home }}/.config/git"
    state: directory
    mode: "0755"

- name: Link git config files
  ansible.builtin.file:
    src: "{{ root }}/git/{{ item }}"
    dest: "{{ home }}/.config/git/{{ item }}"
    state: link
    force: true
  loop:
    - config
    - ignore
