- name: Link git config files
  ansible.builtin.file:
    src: "{{ root }}/git/{{ item }}"
    dest: "{{ home }}/.config/git/{{ item }}"
    state: link
    force: true
  loop:
    - config
    - ignore
