- name: Ensure Hyprland config directory exists
  ansible.builtin.file:
    path: "{{ home }}/.config/hypr"
    state: directory
    mode: "0755"

- name: Link Hyprland configs except runtime variants
  ansible.builtin.file:
    src: "{{ item }}"
    dest: "{{ home }}/.config/hypr/{{ item | basename }}"
    state: link
    force: true
  loop: "{{ lookup('ansible.builtin.fileglob', root + '/hypr/*', wantlist=True) | reject('match', '.*/uwsm$') | list }}"

- name: Ensure UWSM config directory exists
  ansible.builtin.file:
    path: "{{ home }}/.config/uwsm"
    state: directory
    mode: "0755"

- name: Link UWSM configs
  ansible.builtin.file:
    src: "{{ item }}"
    dest: "{{ home }}/.config/uwsm/{{ item | basename }}"
    state: link
    force: true
  loop: "{{ lookup('ansible.builtin.fileglob', root + '/hypr/uwsm/*', wantlist=True) }}"

- name: Install Hyprland packages
  ansible.builtin.package:
    name:
      - uwsm
      - libnewt
      - xdg-desktop-portal-hyprland
      - xdg-desktop-portal-gtk
      - hyprland
      - satty
      - hyprland-qt-support
    state: present
  become: true

- name: Let Hyprland handle the power button
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf
    regexp: "^#?HandlePowerKey=.*$"
    line: "HandlePowerKey=ignore"
  become: true
