- name: Configure Karabiner
  block:
    - name: Create config directory
      ansible.builtin.file:
        path: "{{ home }}/.config/karabiner"
        state: directory
        mode: "0755"

    - name: Link config
      ansible.builtin.file:
        src: "{{ root }}/mac/karabiner/karabiner.json"
        dest: "{{ home }}/.config/karabiner/karabiner.json"
        state: link
        force: true

# Note - Rectangle reads this config once upon first startup, then renames and ignores it.
- name: Configure Rectangle
  block:
    - name: Create config directory
      ansible.builtin.file:
        path: "{{ home }}/Library/Application Support/Rectangle"
        state: directory
        mode: "0755"

    - name: Link config
      ansible.builtin.file:
        src: "{{ root }}/mac/rectangle/RectangleConfig.json"
        dest: "{{ home }}/Library/Application Support/Rectangle/RectangleConfig.json"
        state: link
        force: true

- name: Install macOS-only GUI utilities
  community.general.homebrew_cask:
    name:
      - karabiner-elements
      - raycast
      - rectangle
    state: present
    update_homebrew: false

- name: Apply macOS defaults
  ansible.builtin.shell: |
    # Keyboard shortcuts
    # defaults write -g NSUserKeyEquivalents -dict-add "Lock Screen" "@~^å" # Need a way to represent the Tab key
    defaults write com.apple.finder NSUserKeyEquivalents -dict-add "Close Window" "@q" # Finder has no Quit option
    defaults write com.google.Chrome NSUserKeyEquivalents -dict-add "Close Window" "@~^\$c"
    defaults import com.apple.symbolichotkeys "{{ root }}/mac/misc/symbolichotkeys.plist"

    # Fix Dock
    defaults write com.apple.dock persistent-apps -array # No pinned apps
    defaults write com.apple.dock show-recents -bool false # No recent apps
    defaults write com.apple.dock persistent-others -array # No Downloads shortcut
    defaults write com.apple.dock minimize-to-application -bool false # No app windows
    defaults write com.apple.dock autohide -bool true # Autohide
    defaults write com.apple.dock tilesize -int 1 # Minimum size
    defaults write com.apple.dock autohide-delay -float 1000 # Set delay to about 16 minutes
    defaults write com.apple.dock no-bouncing -bool true # Stop icons bouncing

    # Top-left hot corner starts the screensaver
    defaults write com.apple.dock wvous-tl-corner -int 5
    defaults write com.apple.dock wvous-tl-modifier -int 0

    # Trackpad
    defaults write -g com.apple.swipescrolldirection -bool false # Disable natural scrolling
    defaults write com.apple.AppleMultitouchTrackpad Clicking -int 1 # Tap to click

    # Display and screensaver
    defaults -currentHost write com.apple.screensaver idleTime -int 300 # Show screensaver after five minutes
    sudo pmset displaysleep 10 # Turn off display after ten minutes
    sudo pmset -b lessbright 0 # Do not slightly dim display on battery
    defaults -currentHost write com.apple.screensaver showClock -bool true # Show clock on screensaver
    sudo defaults write /Library/Preferences/com.apple.loginwindow UsesLargeDateTime -bool true # Show clock on lock screen

    # Fix Finder
    defaults write com.apple.finder ShowPathbar -bool true
    defaults write com.apple.finder ShowStatusBar -bool true
    defaults write com.apple.finder FXRemoveOldTrashItems -bool true
    defaults write NSGlobalDomain AppleShowAllExtensions -bool true
    defaults write com.apple.finder NewWindowTargetPath -string "PfHm"
    defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false
    defaults write com.apple.finder ShowRecentTags -bool false
    chflags hidden "{{ home }}/Pictures" "{{ home }}/Documents" "{{ home }}/Music" "{{ home }}/Movies" "{{ home }}/Desktop" "{{ home }}/Public" || true
    defaults write com.apple.finder FXPreferredViewStyle -string "icnv"
    /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:arrangeBy name" ~/Library/Preferences/com.apple.finder.plist
    defaults write com.apple.finder _FXSortFoldersFirst -bool true
    # fd --hidden '^\.DS_Store$' ~ -x rm

    # Miscellaneous
    defaults write ~/Library/Preferences/ByHost/com.apple.controlcenter.plist Bluetooth -int 18 # Use 24 to remove Bluetooth from the menu bar
    defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false # Save to disk instead of iCloud by default
    defaults write NSGlobalDomain KeyRepeat -int 2 # Increase key repeat
    defaults write com.apple.dock mru-spaces -bool false # Do not rearrange Spaces
    defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true # No .DS_Store files on network volumes
    defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true # No .DS_Store files on USB drives
    defaults write com.apple.Spotlight MenuItemHidden -bool true # No Spotlight icon in the menu bar
    mkdir -p ~/Downloads/Screenshots
    defaults write com.apple.screencapture location ~/Downloads/Screenshots
    defaults -currentHost write com.apple.controlcenter.plist BatteryShowPercentage -bool true # Show battery percentage in the menu bar
    touch ~/.hushlogin # Remove last-login message from terminal windows

    # Change hostname
    sudo scutil --set ComputerName "applepie"
    sudo scutil --set HostName "applepie"
    sudo scutil --set LocalHostName "applepie"

    # Restart affected services
    killall Dock || true
    killall SystemUIServer || true
    killall NotificationCenter || true
  changed_when: false
#
# Nota bene - raycast config file password is "password123"
#
# Note to self - main missing functionality
#   No auto-tiling + focus follows mouse
#   No ability to send application to different workspace
#   Workspace switching is slow, but there are apps e.g. space-rabbit that supposedly fix this
