- name: Disable login messages (includes Ubuntu motd and cockpit message)
  ansible.builtin.file:
    path: "{{ home }}/.hushlogin"
    state: touch
    mode: "0644"
    access_time: preserve
    modification_time: preserve
  when: is_headless
  # Note: can also do chmod -x /etc/update-motd.d/*

- name: Configure Fedora DNF defaults
  ansible.builtin.blockinfile:
    path: /etc/dnf/dnf.conf
    marker: "# {mark} ANSIBLE DOTFILES DNF DEFAULTS"
    block: |
      max_parallel_downloads=10
      fastestmirror=True
      defaultyes=True
  become: true
  when: is_fedora

- name: Create some dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ home }}/Downloads/Screenshots"
    - "{{ home }}/Downloads/Videos"
    - "{{ home }}/programs"
    - "{{ home }}/backups"

- name: Install miscellaneous system packages
  ansible.builtin.package:
    name: "{{ pkgs[ansible_facts['os_family']] }}"
    state: present
  become: true
  when: is_managed_desktop and ansible_facts['os_family'] in pkgs
  vars:
    pkgs:
      Archlinux:
        - downgrade
        - reflector

- name: Configure Cockpit
  when: is_headless
  become: true
  block:
    - name: Install Cockpit
      ansible.builtin.package:
        name: cockpit
        state: present

    - name: Enable Cockpit socket
      ansible.builtin.systemd_service:
        name: cockpit.socket
        enabled: true
        state: started
