- name: Install Starship on Arch
  ansible.builtin.package:
    name: starship
    state: present
  become: true
  when: is_arch

- name: Install Starship with Homebrew
  community.general.homebrew:
    name: starship
    state: present
    update_homebrew: false
  environment: "{{ brew_environment }}"
  when: not is_arch

- name: Link Starship config
  ansible.builtin.file:
    src: "{{ root }}/starship/starship.toml"
    dest: "{{ home }}/.config/starship.toml"
    state: link
    force: true
