- name: Install Starship on Arch
  ansible.builtin.package:
    name: starship
    state: present
  become: true
  when: dotfiles_is_arch

- name: Install Starship with Homebrew
  ansible.builtin.command: brew install starship
  environment: "{{ brew_environment }}"
  changed_when: false
  when: not dotfiles_is_arch

- name: Link Starship config
  ansible.builtin.file:
    src: "{{ dotfiles_root }}/starship/starship.toml"
    dest: "{{ dotfiles_home }}/.config/starship.toml"
    state: link
    force: true
