- name: Install Syncthing (Linux)
  ansible.builtin.package:
    name: syncthing
    state: present
  become: true
  when: is_linux

- name: Install Syncthing (Mac/Homebrew)
  community.general.homebrew:
    name: syncthing
    state: present
    update_homebrew: false
  environment: "{{ brew_environment }}"
  when: is_macos

- name: Enable Syncthing as a user service (Desktops)
  ansible.builtin.systemd_service:
    name: syncthing.service
    enabled: true
    state: started
    scope: user
  when: is_linux and not is_server

# System service starts at boot rather than login via graphical session/ssh
- name: Enable Syncthing as a system service (Servers)
  ansible.builtin.systemd_service:
    name: "syncthing@{{ user }}.service"
    enabled: true
    state: started
  become: true
  when: is_linux and is_server
