- name: Install Tailscale on Arch
  ansible.builtin.package:
    name: tailscale
    state: present
  become: true
  when: is_arch

- name: Install Tailscale on Ubuntu and Fedora
  ansible.builtin.shell: |
    curl -fsSL https://tailscale.com/install.sh -o /tmp/tailscale_install.sh
    sh /tmp/tailscale_install.sh
  args:
    creates: /usr/bin/tailscale
  become: true
  when: is_ubuntu or is_fedora

- name: Install Tailscale app on macOS
  community.general.homebrew_cask:
    name: tailscale-app
    state: present
    update_homebrew: false
  environment: "{{ brew_environment }}"
  when: is_macos

- name: Enable tailscaled
  ansible.builtin.systemd_service:
    name: tailscaled.service
    enabled: true
    state: started
  become: true
  when: is_linux

- name: Configure Tailscale SSH operator
  ansible.builtin.command: "tailscale set --ssh --operator={{ user }}"
  become: true
  changed_when: false
  when: is_linux
