- name: Link Waybar config
  ansible.builtin.file:
    src: "{{ dotfiles_root }}/waybar"
    dest: "{{ dotfiles_home }}/.config/waybar"
    state: link
    force: true

- name: Install Waybar
  ansible.builtin.package:
    name: waybar
    state: present
  become: true

- name: Enable Waybar user service
  ansible.builtin.systemd_service:
    name: waybar.service
    enabled: true
    scope: user
