- name: Install Yazi on Arch
  ansible.builtin.package:
    name: yazi
    state: present
  become: true
  when: is_arch

- name: Install Yazi with Homebrew
  ansible.builtin.command: brew install yazi
  environment: "{{ brew_environment }}"
  changed_when: false
  when: not is_arch

- name: Link Yazi config
  ansible.builtin.file:
    src: "{{ root }}/tui/yazi"
    dest: "{{ home }}/.config/yazi"
    state: link
    force: true

- name: Install Yazi packages
  ansible.builtin.command: ya pkg install
  args:
    chdir: "{{ home }}/.config/yazi"
  changed_when: false

- name: Upgrade Yazi packages
  ansible.builtin.command: ya pkg upgrade
  args:
    chdir: "{{ home }}/.config/yazi"
  changed_when: false
