
- link:
    ~/.config/qt6ct/qt6ct.conf: styling/qt/qt6ct.conf

- shell:
  - |
    if [[ "$(./sys id)" == "arch" ]]; then
      sudo pacman -S --noconfirm --needed qt6ct qt5-wayland qt6-wayland breeze breeze-icons
    elif [[ "$(./sys id)" != "arch" ]]; then
      echo "To be added"
    fi


# For qt5 theming
# pacman -S qt5ct breeze5
# Also change qt_qpa_platformtheme to qt5ct and symlink qt5ct.conf file
