[sftp.kabigon]
host = "kabigon"
user = "dominic"
port = 22

[sftp.pikachu]
host = "pikachu"
user = "dominic"
port = 22

[sftp.chocobo]
host = "chocobo"
user = "dominic"
port = 22

[sftp.applepie]
host = "applepie"
user = "dominic"
port = 22

# Usage - I have a keybind for going to chocobo, but for others just type
# yazi sftp://my-server
