#!/usr/bin/env bash

pause_and_continue() {
    echo ""
    read -rp "Press enter to continue... "
}

sign_in_google() {
    read -rp "Would you like to sign in to your Google account? [Y/n] "
    if [[ "${REPLY,,}" =~ ^y$|^$ ]]; then
        xdg-open https://accounts.google.com
        pause_and_continue
    fi
}


login_opencode() {
    read -rp "Would you like to authenticate opencode? [Y/n] "
    if [[ "${REPLY,,}" =~ ^y$|^$ ]]; then
        opencode auth login
        "Don't forget to do :Copilot auth in nvim for gh copilot"
        pause_and_continue
    fi
}

auth_github() {
    read -rp "Would you like to authenticate git and clone repos? [Y/n] "
    if [[ "${REPLY,,}" =~ ^y$|^$ ]]; then
        gh auth login --web -p https
        #TODO clone repos from txt file list
        pause_and_continue
    fi
}

enroll_fingerprints() {
    read -rp "Would you like to enroll fingerprints? [Y/n] "
    if [[ "${REPLY,,}" =~ ^y$|^$ ]]; then
        bash ~/.local/bin/enroll-fingerprints
        pause_and_continue
    fi
}


sign_in_google
login_opencode
auth_github
enroll_fingerprints
# Set up chrome stuff - don't show cards/shortcuts, set wallpaper
# Copy dotfiles env file
# Setup google calender in noctalia
# Syncthing
# If on a new monitor, noctalia widgets/stuff will need to be redone
