#!/bin/env bash
hyprctl dispatch focuswindow "title:^GrandOrgue v.*"
hyprctl dispatch layoutmsg togglesplit
hyprctl dispatch focuswindow "title:^GrandOrgue v.*"
hyprctl dispatch swapwindow u
hyprctl dispatch resizewindowpixel exact 100% 7%, "title:^GrandOrgue v.*"
