- shell:
    # Install github cli
    - |
      if [[ "$(./sys id)" == "arch" ]]; then
        sudo pacman -S --noconfirm --needed github-cli
      elif [[ "$(./sys id)" != "arch" ]]; then
        brew install gh
      fi

    # Authenticate github
    - |
      if ! gh auth status >/dev/null 2>&1; then
          echo "Setting up GitHub auth..."
          mkdir -p ~/.ssh && chmod 700 ~/.ssh
          gh auth login --web -p ssh
          ssh-keyscan -t ed25519 github.com >> ~/.ssh/known_hosts
      else
          echo "GitHub already authenticated. Skipping."
      fi

    # Gh-preview-markdown
    - gh extension install yusukebe/gh-markdown-preview
      # to update - gh extension upgrade markdown-preview
      # to use - gh markdown-preview file.md

    # Repo folders
    - mkdir -p ~/dev/projects ~/dev/external

    # Edit previously cloned repos to have ssh rather than https remotes
    - |
      if [ -d "$HOME/dev/dotfiles" ]; then cd "$HOME/dev/dotfiles" && git remote set-url origin git@github.com:dommcdev/dotfiles.git; fi
     if [ -d "$HOME/dev/wallpapers" ]; then cd "$HOME/dev/wallpapers" && git remote set-url origin git@github.com:dommcdev/wallpapers.git; fi
