- shell:
    - sudo pacman -S --noconfirm --needed qemu-full virt-manager virt-viewer dnsmasq
    - sudo systemctl enable libvirtd
    - sudo usermod -aG libvirt $USER #necessary to prevent polkit auth when opening virt-manager
    - sudo virsh net-autostart default || true #true conditional is for when running in a vm
    - |
      # Force docker to let libvirt traffic through
      # Using -I FORWARD 1 ensures these rules stay at the top of the stack
      sudo iptables -C FORWARD -i virbr0 -j ACCEPT 2>/dev/null || \
      sudo iptables -I FORWARD 1 -i virbr0 -j ACCEPT
      sudo iptables -C FORWARD -o virbr0 -j ACCEPT 2>/dev/null || \
      sudo iptables -I FORWARD 1 -o virbr0 -j ACCEPT

# sudo virsh net-list --all
