all:
  hosts:
    chocobo:
      ansible_host: chocobo
      ansible_become_exe: /usr/bin/sudo.ws
      is_headless: true
      is_hardened: true
      #TODO remove the above stupid workaround once this merges: https://github.com/ansible/ansible/pull/86964
    kabigon:
      ansible_host: kabigon
      is_managed_desktop: true
      is_dev_env: true
      setup_grandorgue: true
    pikachu:
      ansible_host: pikachu
      is_managed_desktop: true
      is_dev_env: true
      has_battery: true
      has_fingerprint_reader: true
      setup_grandorgue: true
    arch:
      ansible_host: 192.168.122.165
      ansible_user: arch
      is_managed_desktop: true
      is_dev_env: true
      setup_grandorgue: true
    cachyos:
      ansible_host: 192.168.122.232
      ansible_user: cachyos
      is_managed_desktop: true
      is_dev_env: true
      setup_grandorgue: true
    ubuntu:
      ansible_become_exe: /usr/bin/sudo.ws
      ansible_host: 192.168.122.176
      ansible_user: dominic
      is_managed_desktop: true
      is_dev_env: true
      setup_grandorgue: true
    fedora:
      ansible_host: 192.168.122.155
      ansible_user: dominic
      is_managed_desktop: true
      is_dev_env: true
      setup_grandorgue: true

  vars:
    ansible_connection: "{{ 'local' if inventory_hostname == lookup('pipe', 'hostname -s') else 'ssh' }}"
    home: "{{ ansible_facts['env']['HOME'] }}"
    root: "{{ home }}/dev/dotfiles"
    user: "{{ ansible_facts['user_id'] }}"

    # Restate some Ansible gathered facts for greater ease of use
    is_arch: "{{ ansible_facts['os_family'] == 'Archlinux' }}"
    is_ubuntu: "{{ ansible_facts['os_family'] == 'Debian' }}"
    is_fedora: "{{ ansible_facts['os_family'] == 'RedHat' }}"
    is_macos: "{{ ansible_facts['system'] == 'Darwin' }}"
    is_linux: "{{ ansible_facts['system'] == 'Linux' }}"

    # Inventory-defined facts
    is_headless: false
    is_managed_desktop: false
    is_dev_env: false
    is_hardened: false
    has_battery: false
    has_fingerprint_reader: false
    manage_gpu: true
    setup_grandorgue: false
