all:
  hosts:
    chocobo:
      ansible_host: chocobo.tetra-salmon.ts.net
    kabigon:
      ansible_host: kabigon.tetra-salmon.ts.net
    pikachu:
      ansible_host: pikachu.tetra-salmon.ts.net

  children:
    servers:
      hosts:
        chocobo:

    desktops:
      hosts: {}

    custom:
      hosts:
        kabigon:
        pikachu:

    laptops:
      hosts:
        pikachu:
