- name: Configure machines
  hosts: all
  gather_facts: true

  vars_files:
    - .secrets.yml

  vars:
    ansible_become_password: "{{ become_passwords[inventory_hostname] }}"

  pre_tasks: []

  tasks:
    - name: Script links
      ansible.builtin.include_tasks: tasks/apps/scripts.yml
    - name: Syncthing
      ansible.builtin.include_tasks: tasks/apps/syncthing.yml
    - name: Network
      ansible.builtin.include_tasks: tasks/system/network.yml
      when: is_managed_desktop
