export EDITOR="nvim"
export VISUAL="nvim" #Fallback for editor
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.local/share/npm-global/bin:$PATH"
export ZDOTDIR="$HOME/.config/zsh"
export ANDROID_HOME="$HOME/programs/Android/Sdk"
