typeset -gU path PATH #no path duplicates!

export EDITOR="nvim"
export VISUAL="nvim" #Fallback for editor
export ZDOTDIR="$HOME/.config/zsh"
export ANDROID_HOME="$HOME/programs/Android/Sdk"
export GOPATH="$HOME/.local/share/go"
export BUN_INSTALL="$HOME/.local/share/bun" #set this for good measure

# Set these for ssh
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"

export PATH="$PATH:$GOPATH/bin"
export PATH="$HOME/.local/share/npm-global/bin:$PATH"
export PATH="$BUN_INSTALL/bin:$PATH"
# Homebrew for non-interactive shells
if [[ -d /home/linuxbrew/.linuxbrew ]]; then
    export HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew"
    export HOMEBREW_CELLAR="$HOMEBREW_PREFIX/Cellar"
    export HOMEBREW_REPOSITORY="$HOMEBREW_PREFIX/Homebrew"
    export PATH="$HOMEBREW_PREFIX/bin:$HOMEBREW_PREFIX/sbin${PATH+:$PATH}"
fi
export PATH="$HOME/.local/bin:$PATH"


[[ -f "$HOME/.config/zsh/.zshenv.local" ]] && source "$HOME/.config/zsh/.zshenv.local"
