# Main zsh options
HISTFILE=~/.histfile
HISTSIZE=5000
SAVEHIST=5000

setopt autocd #cd by typing dir name
unsetopt beep #no beeping!
bindkey -v
autoload -Uz compinit
compinit


# Visuals
PS1="%{%F{green}%}%n@%m %{%F{yellow}%}%2~ %{%F{reset}%}%% "


# Aliases
alias ls='ls --color=auto'
alias la='ls -lAh --color=auto --group-directories-first'
alias grep='grep --color=auto'
alias vi='nvim'
alias vim='nvim'
alias fs='fastfetch'
alias c='clear' #note - ctrl+L will also clear!
alias wth='curl wttr.in'
alias pwd='pwd && pwd | wl-copy'
alias rm='trash-put'
alias quit='exit'
alias stow='stow --dotfiles'
alias cat='bat'
alias mv='mv -i'
alias cp='cp -i'
alias showpath='echo $PATH | tr ":" "\n"'

# Env variables
export PATH="$HOME/.local/bin:$PATH"
export EDITOR="nvim"
export VISUAL="nvim" #Fallback for editor



# FZF configuration
source <(fzf --zsh)


# Run yazi with 'y', change cwd when exiting yazi
function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	IFS= read -r -d '' cwd < "$tmp"
	[ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
	rm -f -- "$tmp"
}


# Part of nvm installation
export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
