# Main zsh options
HISTFILE=~/.histfile
HISTSIZE=5000
SAVEHIST=5000

# Set a bar-shaped cursor in tmux/shell
precmd() {
  printf "\e[5 q"
}

setopt autocd #cd by typing dir name
unsetopt beep #no beeping!
autoload -Uz compinit
compinit


# Visuals
PS1="%{%F{green}%}%n@%m %{%F{yellow}%}%2~ %{%F{reset}%}%% "


# Aliases
alias ls='eza'
alias la='eza -la'
alias lst='eza --tree'
alias grep='grep --color=auto'
alias vi='nvim'
alias vim='nvim'
alias fs='fastfetch'
alias c='clear'
alias wth='curl wttr.in'
alias pwd='pwd && pwd | wl-copy'
alias rm='trash-put'
alias cat='bat'
alias mv='mv -i'
alias cp='cp -i'
alias showpath='echo $PATH | tr ":" "\n"'
alias df="df -h"
alias du="du -h -d 1"

# Env variables
export PATH="$HOME/.local/bin:$PATH"
export EDITOR="nvim"
export VISUAL="nvim" #Fallback for editor



# FZF configuration
source <(fzf --zsh)
# Unbind the default Alt-C keybinding for fzf-cd-widget
bindkey -rM emacs '^[^C'
bindkey -rM vicmd '^[^C'
bindkey -rM viins '^[^C'
# Bind fzf-cd-widget to Ctrl-E
bindkey -M emacs '^G' fzf-cd-widget
bindkey -M vicmd '^G' fzf-cd-widget
bindkey -M viins '^G' fzf-cd-widget

# Better zsh-vi-mode
#source /usr/share/zsh/plugins/zsh-vi-mode/zsh-vi-mode.plugin.zsh

# Zoxide
eval "$(zoxide init --cmd cd zsh)"

# Run yazi with 'y', change cwd when exiting yazi
function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	IFS= read -r -d '' cwd < "$tmp"
	[ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
	rm -f -- "$tmp"
}

# Part of nvm installation
export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Last but certainly not least...:)
fastfetch
