- name: Configure GTK, Qt, and icon appearance
  block:
    - name: Install packages
      ansible.builtin.package:
        name: "{{ pkgs[ansible_facts['os_family']] }}"
        state: present
      become: true
      when: ansible_facts['os_family'] in pkgs
      vars:
        pkgs:
          Archlinux:
            - adw-gtk-theme
            - breeze
            - breeze-icons
            - papirus-icon-theme
          Debian:
            - breeze
            - breeze-icon-theme
            - papirus-icon-theme
            - qt6ct
          RedHat:
            - adw-gtk3-theme
            - plasma-breeze
            - breeze-icon-theme
            - papirus-icon-theme
            - qt6ct

    - name: Install Qt configuration tool on Arch
      become: true
      become_user: aur_builder
      kewlfft.aur.aur:
        name: qt6ct-kde
        state: present
      when: is_arch

    - name: Download Papirus Folders installer
      ansible.builtin.get_url:
        url: https://git.io/papirus-folders-install
        dest: /tmp/papirus-folders-install.sh
        mode: "0755"

    - name: Install Papirus Folders
      ansible.builtin.command: /tmp/papirus-folders-install.sh
      args:
        creates: /usr/bin/papirus-folders
      become: true

    - name: Configure Papirus folder color
      ansible.builtin.command: papirus-folders -C orange --theme Papirus-Dark
      become: true
      changed_when: false

    - name: Create config directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ home }}/.config/qt6ct"
        - "{{ home }}/.config/gtk-3.0"
        - "{{ home }}/.config/gtk-4.0"

    - name: Link config files
      ansible.builtin.file:
        src: "{{ root }}/appearance/{{ item.src }}"
        dest: "{{ home }}/.config/{{ item.dest }}"
        state: link
        force: true
      loop:
        - src: gtk/gtk.css
          dest: gtk-3.0/gtk.css
        - src: gtk/gtk.css
          dest: gtk-4.0/gtk.css
        - src: gtk/settings.ini
          dest: gtk-4.0/settings.ini
        - src: templates
          dest: templates
        - src: user-dirs.dirs
          dest: user-dirs.dirs
        - src: mimeapps.list
          dest: mimeapps.list
        - src: gtk/bookmarks
          dest: gtk-3.0/bookmarks
        - src: qt/qt6ct.conf
          dest: qt6ct/qt6ct.conf

    - name: Configure Flatpak GTK filesystem overrides
      ansible.builtin.command: "flatpak override --user --filesystem={{ item }}"
      changed_when: false
      loop:
        - xdg-config/gtk-4.0
        - xdg-config/gtk-3.0

    - name: Configure desktop appearance
      ansible.builtin.command: "gsettings set org.gnome.desktop.interface {{ item.key }} {{ item.value }}"
      changed_when: false
      loop:
        - key: gtk-theme
          value: adw-gtk3
        - key: color-scheme
          value: prefer-dark
        - key: icon-theme
          value: Papirus-Dark

# Note: If changing the cursor, also update `uwsm/env` and the cursor block in the Noctalia greeter config.
# Breeze cursors are installed as part of each distro's general breeze megapackage installed above
- name: Configure mouse cursor
  block:
    - name: Create default cursor directory
      ansible.builtin.file:
        path: "{{ home }}/.local/share/icons/default"
        state: directory
        mode: "0755"

    - name: Configure cursor for Xwayland apps
      ansible.builtin.copy:
        dest: "{{ home }}/.local/share/icons/default/index.theme"
        mode: "0644"
        content: |
          [Icon Theme]
          Name=Default
          Comment=Default Cursor Theme
          Inherits=breeze_cursors

# TODO adw-gtk on Debian, qt6ct-kde on Debian/Fedora
