- name: Install desktop integration packages
  ansible.builtin.package:
    name: "{{ pkgs[ansible_facts['os_family']] }}"
    state: present
  become: true
  when: ansible_facts['os_family'] in pkgs
  vars:
    pkgs:
      Archlinux:
        - accountsservice
        - xdg-utils
        - ddcutil
        - wl-clipboard
        - gnome-keyring
        - libsecret
        - wtype
        - brightnessctl
        - acpi
        - udiskie
        - wev
        - libinput-tools
      RedHat:
        - xdg-utils
        - ddcutil
        - wl-clipboard
        - gnome-keyring
        - libsecret
        - wtype
        - brightnessctl
        - acpi
        - udiskie
        - wev
        - libinput-utils

- name: Configure desktop storage support
  block:
    - name: Install filesystem and storage packages
      ansible.builtin.package:
        name: "{{ pkgs[ansible_facts['os_family']] }}"
        state: present
      become: true
      when: ansible_facts['os_family'] in pkgs
      vars:
        pkgs:
          Archlinux:
            - smartmontools
            - dosfstools
            - ntfs-3g
            - exfatprogs
            - btrfs-progs
            - xfsprogs
          Debian:
            - smartmontools
            - dosfstools
            - ntfs-3g
            - exfatprogs
            - btrfs-progs
            - xfsprogs
          RedHat:
            - smartmontools
            - dosfstools
            - ntfs-3g
            - exfatprogs
            - btrfs-progs
            - xfsprogs
