- name: Install network packages
  ansible.builtin.package:
    name: "{{ pkgs[ansible_facts['os_family']] }}"
    state: present
  become: true
  when: ansible_facts['os_family'] in pkgs
  vars:
    pkgs:
      Archlinux:
        - networkmanager
        - nm-connection-editor
        - iwd
        - inetutils
        - nftables
        - iptables
      Debian:
        - network-manager
        - network-manager-gnome
        - iwd
        - inetutils-tools
        - systemd-resolved
        - nftables
        - iptables
      RedHat:
        - NetworkManager
        - NetworkManager-wifi
        - nm-connection-editor
        - iwd
        - systemd-resolved
        - nftables
        - iptables-nft

- name: Create NetworkManager config directory
  ansible.builtin.file:
    path: /etc/NetworkManager/conf.d
    state: directory
    mode: "0755"
  become: true

- name: Copy NetworkManager config
  ansible.builtin.copy:
    src: "{{ root }}/network/networkmanager.conf"
    dest: /etc/NetworkManager/conf.d/90-dotfiles.conf
    mode: "0644"
  become: true
  register: networkmanager_config

- name: Disable NetworkManager wait online to speed up boot
  ansible.builtin.systemd_service:
    name: NetworkManager-wait-online.service
    enabled: false
    masked: true
  become: true

- name: Enable systemd-resolved
  ansible.builtin.systemd_service:
    name: systemd-resolved.service
    enabled: true
    state: started
  become: true

- name: Link systemd-resolved stub resolver
  ansible.builtin.file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: true
  become: true

- name: Enable/restart NetworkManager
  ansible.builtin.systemd_service:
    name: NetworkManager.service
    enabled: true
    state: "{{ 'restarted' if networkmanager_config.changed else 'started' }}"
  become: true
