- name: Install network packages
  ansible.builtin.package:
    name: "{{ pkgs[ansible_facts['os_family']] }}"
    state: present
  become: true
  when: ansible_facts['os_family'] in pkgs
  vars:
    pkgs:
      Archlinux:
        - networkmanager
        - network-manager-applet
        - nm-connection-editor
        - iwd
        - inetutils
        - nftables
        - iptables
        - avahi
      Debian:
        - network-manager
        - network-manager-gnome
        - iwd
        - inetutils-tools
        - systemd-resolved
        - nftables
        - iptables
        - avahi-daemon
      RedHat:
        - NetworkManager
        - NetworkManager-wifi
        - network-manager-applet
        - nm-connection-editor
        - iwd
        - systemd-resolved
        - nftables
        - iptables-nft
        - avahi

- name: Configure NetworkManager
  block:
    - name: Create config directory
      ansible.builtin.file:
        path: /etc/NetworkManager/conf.d
        state: directory
        mode: "0755"
      become: true

    - name: Copy config
      ansible.builtin.copy:
        dest: /etc/NetworkManager/conf.d/90-dotfiles.conf
        mode: "0644"
        content: |
          [main]
          dns=systemd-resolved

          [keyfile]
          unmanaged-devices=interface-name:tailscale0

          [device]
          wifi.backend=iwd

          [connectivity]
          uri=http://connectivity-check.ubuntu.com/
      become: true
      register: networkmanager_config

    - name: Disable NetworkManager-wait-online to speed up boot
      ansible.builtin.systemd_service:
        name: NetworkManager-wait-online.service
        enabled: false
        masked: true
      become: true

- name: Configure systemd-resolved (set mDNS to resolve-only + Cloudflare for DNS)
  block:
    - name: Create resolved override directory
      ansible.builtin.file:
        path: /etc/systemd/resolved.conf.d
        state: directory
        mode: "0755"
      become: true

    - name: Copy config
      ansible.builtin.copy:
        dest: /etc/systemd/resolved.conf.d/10-global.conf
        mode: "0644"
        content: |
          [Resolve]
          # Primary & Secondary DNS (Cloudflare)
          DNS=1.1.1.1#cloudflare-dns.com 1.0.0.1#cloudflare-dns.com 2606:4700:4700::1111#cloudflare-dns.com 2606:4700:4700::1001#cloudflare-dns.com
          DNSOverTLS=opportunistic

          ## Allow systemd-resolved to resolve mDNS names, but do not advertise/register
          # this machine over mDNS. Avahi is the sole mDNS advertiser/responder.
          MulticastDNS=resolve
          LLMNR=no
      become: true
      register: resolved_config

- name: Enable/restart systemd-resolved
  ansible.builtin.systemd_service:
    name: systemd-resolved.service
    enabled: true
    state: "{{ 'restarted' if resolved_config.changed else 'started' }}"
  become: true

- name: Enable Avahi
  ansible.builtin.systemd_service:
    name: avahi-daemon.service
    enabled: true
    state: started
  become: true

- name: Link systemd-resolved stub resolver
  ansible.builtin.file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: true
  become: true

- name: Enable TCP MTU probing
  ansible.builtin.lineinfile:
    path: /etc/sysctl.d/99-sysctl.conf
    line: net.ipv4.tcp_mtu_probing=1
    create: true
    mode: "0644"
  become: true
  when: is_linux

- name: Enable/restart NetworkManager
  ansible.builtin.systemd_service:
    name: NetworkManager.service
    enabled: true
    state: "{{ 'restarted' if networkmanager_config.changed else 'started' }}"
  become: true
#
# Debugging: nmcli, (networkctl status), ip link, ip route, ip addr
# TODO might need to disable/mask wpa_supplicant depending on distro. Also, wait after restarting networkmanager?
