- name: Install printing packages
  ansible.builtin.package:
    name: "{{ pkgs[ansible_facts['os_family']] }}"
    state: present
  become: true
  when: ansible_facts['os_family'] in pkgs
  vars:
    pkgs:
      Archlinux:
        - cups
        - cups-browsed
        - cups-filters
        - cups-pdf
        - system-config-printer
        - cups-pk-helper
      Debian:
        - cups
        - cups-browsed
        - cups-filters
        - printer-driver-cups-pdf
        - system-config-printer
        - cups-pk-helper
      RedHat:
        - cups
        - cups-browsed
        - cups-filters
        - cups-pdf
        - system-config-printer
        - cups-pk-helper

- name: Enable remote printer discovery
  ansible.builtin.lineinfile:
    path: /etc/cups/cups-browsed.conf
    line: "CreateRemotePrinters Yes"
  become: true
  register: cups_browsed_config

- name: Enable/restart printing services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    state: "{{ 'restarted' if item == 'cups-browsed.service' and cups_browsed_config.changed else 'started' }}"
  become: true
  loop:
    - cups.service
    - cups-browsed.service
